### ISSUE TITLE
 [BUG] CPU stuck at max 1794 Mhz

### ISSUE THREAD

**Issue by batyliit** [ananjaser1211/FloydT_Reports#26]
**Description of the Bug**
Stuck at 1794 Mhz. Only using little cores, hardly any of the big 

**Screenshots**
![Screenshot_20240606_100734_Geekbench 6](https://github.com/ananjaser1211/FloydT_Reports/assets/163852366/1cf045fe-6449-4710-ab16-2f92122448f5)
![Screenshot_20240606_100740_Geekbench 6](https://github.com/ananjaser1211/FloydT_Reports/assets/163852366/76eda269-6a83-4ead-9a84-a3b562a5748f)
![Screenshot_20240606_101206_Geekbench 6](https://github.com/ananjaser1211/FloydT_Reports/assets/163852366/ddda2ba2-2338-4347-90c4-fae513b23b4c)

**Smartphone**
 - Device: Galaxy S9
 - Model: G960F

**Additional Information**
Even tried setting 2704 Mhz in kernel manager xxTR

**Comment by mutchiko** [comment]
This issue can be fixed with  xxTR Manager:

1. if you have hKtweaks installed, then uninstall it.
3. make sure that xxTR Manager settings are default. if not, you can change them by clicking Restore application in the settings page for the app.
5. go to the CPU Hotplug page.
6. HotPlug Mode is 0 by default. change that to 1.
7. go to the CPU page and check big cores frequencies, you might need to set CPU Maximum Frequency to 2704 Mhz.

please test and update us.

**Comment by duhansysl** [comment]
@mutchiko we longtermly tested this with anan, back then it had caused serious heat problems so be aware of that while testing this. also let us know if there is heat & heavy battery usage so we ccan update it or not

**Comment by mutchiko** [comment]
@duhansysl i wanted to test with governors other than schedutil, but i was surprised when i found out it was the only one available, i wonder why...

**Comment by mutchiko** [comment]
i tested HotPlug Mode at 1 yesterday, and it wasn't the best experience:

- CPU heats to 55~65 on normal use (which is too much)
- it clocks to 2704 Mhz even for simple tasks, avoiding a lot of frequency steps
-  the performance actually degrades instead of improving, stutters happen even in home screen

i also tested HotPlug at 3, which locks the frequency just like 0. it improves the performance and the entire phone experience becomes very responsive overall, but i get the same temps as with HotPlug at 1.

i didn't mention the battery here because it's not calibrated yet.

**Comment by duhansysl** [comment]
@mutchiko as i told you, we had tested this long ago and we faced those issues and thats why we set them up like this. better to turn it off for better use

**Comment by ananjaser1211** [comment]
Exynos 9810 M3 cores are very power hungry, so they rarely run at 2.7ghz, there are 3 modes, Base freq is 1.79GHz, triple and quad core freq is also 1.79GHz

Single load is 2.7GHz, and dual core load is 2.3GHz, the cpu will run at 1.79GHz 90~95% of the time, and will only switch to 2.3/2.7 when its installing apps, sometimes when lunching apps, and in certain games that dont load all 4 cores at once.

this is the stock hotplug/cpu behaviour, if you wish to run at 1.9/2.3 or 2.7 you will find better luck using xxTr kernel and manager, as part of overriding the limitation is in the kernel not only manager app

FYI when hotplug is disabled the big cores will also be limited to 1.79GHz unless you override hotplug mode, which again will just cause overheating and battery drain.

Also keep in mind for the first ~15mins or so of boot, the cpu will also be locked to 1.79 because there is heavy all core load (android dex optimizations etc) so if you run a benchmark during that period it will be at 1.79ghz, which is very slow.

Attached is GB6 benchmark score.

![photo_2024-06-22_18-50-30](https://github.com/ananjaser1211/FloydT_Reports/assets/25624482/8e4066c2-3038-4f28-8ef0-ac2d48eab805)
